"""add names to cart table

Revision ID: 10d9d7d1d161
Revises: b252dac238c0
Create Date: 2025-09-22 21:00:39.306869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d9d7d1d161'
down_revision: Union[str, Sequence[str], None] = 'b252dac238c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'name')
    # ### end Alembic commands ###
